# Generated by Django 5.0.14 on 2026-09-24 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_alumno', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id_examen', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_agente', models.CharField(max_length=150)),
                ('tiempo_limite', models.PositiveIntegerField(help_text='segundos')),
                ('puntaje_minimo', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pista',
            fields=[
                ('id_pista', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pista', models.CharField(max_length=150)),
                ('definicion', models.TextField()),
                ('costo_exp', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recompensa',
            fields=[
                ('id_recompensa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_recompensa', models.CharField(max_length=150)),
                ('puntos_requeridos', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reto',
            fields=[
                ('id_reto', models.AutoField(primary_key=True, serialize=False)),
                ('recompensa_exp', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id_ruta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ruta', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ComprarPista',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_transaccion', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_pista', to='recode.alumno')),
                ('pista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='recode.pista')),
            ],
        ),
        migrations.CreateModel(
            name='ProgresoAlumno',
            fields=[
                ('id_progreso', models.AutoField(primary_key=True, serialize=False)),
                ('puntos_exp', models.PositiveIntegerField(default=0)),
                ('nivel', models.PositiveIntegerField(default=1)),
                ('racha', models.PositiveIntegerField(default=0)),
                ('alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progreso', to='recode.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='ResolverExamen',
            fields=[
                ('id_intento_examen', models.AutoField(primary_key=True, serialize=False)),
                ('numero_intento', models.PositiveIntegerField(default=1)),
                ('puntaje_obtenido', models.PositiveIntegerField(default=0)),
                ('aprobado', models.BooleanField(default=False)),
                ('fecha_intento', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos_examen', to='recode.alumno')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='recode.examen')),
            ],
        ),
        migrations.CreateModel(
            name='RetoCF',
            fields=[
                ('reto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='recode.reto')),
                ('id_reto_cf', models.AutoField(primary_key=True, serialize=False)),
                ('estructura_frase', models.JSONField()),
            ],
            bases=('recode.reto',),
        ),
        migrations.CreateModel(
            name='RetoCifrado',
            fields=[
                ('reto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='recode.reto')),
                ('id_reto_ci', models.AutoField(primary_key=True, serialize=False)),
                ('acertijo_logico', models.JSONField()),
            ],
            bases=('recode.reto',),
        ),
        migrations.CreateModel(
            name='RetoDD',
            fields=[
                ('reto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='recode.reto')),
                ('id_reto_dd', models.AutoField(primary_key=True, serialize=False)),
                ('catalogo_dd', models.JSONField()),
            ],
            bases=('recode.reto',),
        ),
        migrations.CreateModel(
            name='RetoDecision',
            fields=[
                ('reto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='recode.reto')),
                ('id_reto_dc', models.AutoField(primary_key=True, serialize=False)),
                ('opciones_botones', models.JSONField()),
            ],
            bases=('recode.reto',),
        ),
        migrations.CreateModel(
            name='ResolverReto',
            fields=[
                ('id_resolucion', models.AutoField(primary_key=True, serialize=False)),
                ('completado_exitosamente', models.BooleanField(default=False)),
                ('fecha_resolucion', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resoluciones_reto', to='recode.alumno')),
                ('reto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resoluciones', to='recode.reto')),
            ],
            options={
                'ordering': ['-fecha_resolucion'],
            },
        ),
        migrations.AddField(
            model_name='pista',
            name='reto',
            field=models.ForeignKey(db_column='id_reto', on_delete=django.db.models.deletion.CASCADE, related_name='pistas', to='recode.reto'),
        ),
        migrations.AddField(
            model_name='examen',
            name='ruta',
            field=models.ForeignKey(db_column='id_ruta', on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='recode.ruta'),
        ),
        migrations.CreateModel(
            name='Subtema',
            fields=[
                ('id_subtema', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_subtema', models.CharField(max_length=150)),
                ('ruta', models.ForeignKey(db_column='id_ruta', on_delete=django.db.models.deletion.CASCADE, related_name='subtemas', to='recode.ruta')),
            ],
        ),
        migrations.AddField(
            model_name='reto',
            name='subtema',
            field=models.ForeignKey(db_column='id_subtema', on_delete=django.db.models.deletion.CASCADE, related_name='retos', to='recode.subtema'),
        ),
        migrations.CreateModel(
            name='ReclamarRecompensa',
            fields=[
                ('id_reclamo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reclamo', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recompensas_reclamadas', to='recode.alumno')),
                ('recompensa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamos', to='recode.recompensa')),
            ],
            options={
                'unique_together': {('alumno', 'recompensa')},
            },
        ),
    ]
