# Generated by Django 5.0.14 on 2026-09-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recode', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reto',
            options={'ordering': ['subtema', 'orden']},
        ),
        migrations.AddField(
            model_name='reto',
            name='orden',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='reto',
            unique_together={('subtema', 'orden')},
        ),
    ]
