# Generated by Django 5.0.14 on 2026-09-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recode', '0002_alter_reto_options_reto_orden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
