# Generated by Django 5.0.14 on 2026-09-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recode', '0003_ruta_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtema',
            options={'ordering': ['ruta', 'orden']},
        ),
        migrations.AddField(
            model_name='subtema',
            name='orden',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
