# Generated by Django 5.0.14 on 2026-09-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recode', '0004_alter_subtema_options_subtema_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='reto',
            name='pista',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reto',
            name='retro_correcta',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reto',
            name='retro_incorrecta',
            field=models.TextField(blank=True, default=''),
        ),
    ]
